In [10]:
import pandas as pd
import numpy as np
import os 
from sklearn.preprocessing import StandardScaler

In [21]:
# Before running this cell , make sure you run createFolder.py and you run this file in this dataCleaning folder, which is inside notebook folder
with open("dataFolder.txt",'r') as f:
    folder = f.read()

In [3]:
filePath = os.path.join(folder,"08_investor_transactions.csv")

In [4]:
df = pd.read_csv(filePath)

In [5]:
df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [8]:
df['transaction_type'].value_counts()

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [9]:
df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

## Standardize Transaction_type

In [11]:
df['transaction_type'].unique()

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

## Validate amount>0

In [12]:
df[df['amount_inr']<=0]

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status]
Index: []

## Fix dates format

In [13]:
df.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [14]:
df['transaction_date']

0        2024-01-01
1        2024-01-01
2        2024-01-01
3        2024-01-01
4        2024-01-01
            ...
32773    2025-05-30
32774    2025-05-30
32775    2025-05-30
32776    2025-05-30
32777    2025-05-30
Name: transaction_date, Length: 32778, dtype: object

In [15]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [16]:
df.dtypes

investor_id                   object
transaction_date      datetime64[ns]
amfi_code                      int64
transaction_type              object
amount_inr                     int64
state                         object
city                          object
city_tier                     object
age_group                     object
gender                        object
annual_income_lakh           float64
payment_mode                  object
kyc_status                    object
dtype: object

## check KYC status enum values

In [18]:
df['kyc_status'].unique()

array(['Verified', 'Pending'], dtype=object)

In [19]:
df['kyc_status'].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [20]:
df['kyc_status'].isnull().sum()

np.int64(0)

In [24]:
df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [25]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_investor_transaction.csv"),index=False)