In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Before running this cell , make sure you run createFolder.py and you run this file in this dataCleaning folder, which is inside notebook folder
with open("dataFolder.txt",'r') as f:
    folder = f.read()

In [3]:
folder

'C:\\Users\\dell\\OneDrive\\Desktop\\mutual-fund-capstone\\data\\raw'

In [4]:
filePath = os.path.join(folder,"01_fund_master.csv")

In [5]:
df = pd.read_csv(filePath)

In [6]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [7]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [8]:
df.dtypes

amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

In [10]:
df.shape

(40, 15)

In [12]:
df.drop_duplicates(inplace = True)

In [14]:
df['amfi_code'].nunique()

40

In [16]:
df['benchmark'].value_counts()

benchmark
NIFTY 100 TRI                   14
BSE 250 SmallCap TRI             6
NIFTY Midcap 150 TRI             6
NIFTY 500 TRI                    4
CRISIL Liquid Fund AI Index      3
CRISIL Dynamic Gilt Index        2
NIFTY 50 TRI                     2
CRISIL Short Term Bond Index     1
NIFTY Midcap 50 TRI              1
NIFTY Large Midcap 250 TRI       1
Name: count, dtype: int64

In [17]:
df['category'].value_counts()

category
Equity    34
Debt       6
Name: count, dtype: int64

In [18]:
df['exit_load_pct'].dtype

dtype('float64')

In [20]:
import matplotlib.pyplot as plt

In [26]:
df['exit_load_pct'].describe()['75%']

np.float64(1.0)

In [36]:
Q1 = df['exit_load_pct'].describe()['25%']
Q3 = df['exit_load_pct'].describe()['75%']
lower_bound = Q1 - (1.5*(Q3-Q1))
upper_bound  = Q3 + (1.5*(Q3-Q1))
df[df['exit_load_pct']<lower_bound]

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02
9,100025,HDFC Mutual Fund,HDFC Short Term Debt Fund - Regular - Growth,Debt,Short Duration,Regular,2002-06-25,CRISIL Short Term Bond Index,0.56,0.5,500,1000,Anil Bamboli,Low,DC02
14,120507,ICICI Prudential MF,ICICI Pru Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2001-11-17,CRISIL Liquid Fund AI Index,0.74,0.0,500,5000,Rahul Goswami,Low,DC01
18,118635,Nippon India MF,Nippon India ETF Nifty 50 BeES,Equity,Index/ETF,Direct,2001-12-28,NIFTY 50 TRI,0.89,0.0,500,100,Vishal Jain,Moderate,EI01
19,118636,Nippon India MF,Nippon India Gilt Securities Fund - Regular - ...,Debt,Gilt,Regular,1999-08-19,CRISIL Dynamic Gilt Index,0.55,0.0,500,1000,Vivek Sharma,Low,DC02
23,120844,Kotak Mahindra MF,Kotak Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2004-03-03,CRISIL Liquid Fund AI Index,0.60,0.0,500,5000,Deepak Agrawal,Low,DC01
30,101208,Aditya Birla Sun Life MF,ABSL Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2000-04-17,CRISIL Liquid Fund AI Index,0.79,0.0,500,5000,Maneesh Dangi,Low,DC01
31,102885,UTI Mutual Fund,UTI Nifty 50 Index Fund - Regular - Growth,Equity,Index,Regular,2000-03-06,NIFTY 50 TRI,1.57,0.0,500,1000,Sharwan Kumar Goyal,Moderate,EI01

In [35]:
df[df['exit_load_pct']>upper_bound].shape[0]

0

# Creation of column that flags the anomaly

In [40]:
df['exit_load_pct_anomaly']= df['exit_load_pct'].apply(lambda g:True if (g<lower_bound or g>upper_bound) else False)

In [41]:
df.shape

(40, 16)

In [199]:
def flag_anomaly(columns):
    for column in columns:
        Q1 = df[column].describe()['25%']
        Q3 = df[column].describe()['75%']
        lower_bound = Q1 - (1.5*(Q3-Q1))
        upper_bound  = Q3 + (1.5*(Q3-Q1))
        df[f"{column}_anomaly"] = (
            (df[column] < lower_bound) |
            (df[column] > upper_bound)
        )
        if df[df[f"{column}_anomaly"]==True].empty:
            df.drop(f"{column}_anomaly", axis=1,inplace=True)

In [45]:
flag_anomaly(df.describe().columns)

In [46]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code,exit_load_pct_anomaly,amfi_code_anomaly,expense_ratio_pct_anomaly,min_sip_amount_anomaly,min_lumpsum_amount_anomaly
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False,False
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False,False
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False,False
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False,False
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02,True,False,False,False,False

In [48]:
df.drop('amfi_code_anomaly',axis=1,inplace = True)

In [49]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code,exit_load_pct_anomaly,expense_ratio_pct_anomaly,min_sip_amount_anomaly,min_lumpsum_amount_anomaly
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02,True,False,False,False

In [50]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_fund_master.csv"),index=False)

In [51]:
df  = pd.read_csv(os.path.join(folder,"03_aum_by_fund_house.csv"))

In [52]:
df.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [53]:
df = pd.read_csv(os.path.join(os.path.dirname(folder),"processed",'c_fund_master.csv'))

In [54]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code,exit_load_pct_anomaly,expense_ratio_pct_anomaly,min_sip_amount_anomaly,min_lumpsum_amount_anomaly
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01,False,False,False,False
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03,False,False,False,False
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02,True,False,False,False

In [56]:
df['launch_date']=pd.to_datetime(df['launch_date'])

In [58]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_fund_master.csv"),index=False)

In [59]:
df  = pd.read_csv(os.path.join(folder,"03_aum_by_fund_house.csv"))

In [60]:
df.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [61]:
df.dtypes

date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [62]:
df['date'] = pd.to_datetime(df['date'])

In [63]:
df['fund_house'].unique()

array(['SBI Mutual Fund', 'ICICI Prudential MF', 'HDFC Mutual Fund',
       'Nippon India MF', 'Kotak Mahindra MF', 'Aditya Birla Sun Life MF',
       'Axis Mutual Fund', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [67]:
col = df.describe().columns[1:]

In [68]:
flag_anomaly(col)

In [69]:
df.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,aum_lakh_crore_anomaly,aum_crore_anomaly,num_schemes_anomaly
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,False,False,False
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,False,False,False
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,False,False,False
3,2022-03-31,Nippon India MF,2.70,270000,177,False,False,False
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,False,False,False

In [77]:
df[df['aum_crore_anomaly']==True]

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,aum_lakh_crore_anomaly,aum_crore_anomaly
50,2024-09-30,SBI Mutual Fund,10.80,1080000,186,True,True
60,2024-12-31,SBI Mutual Fund,11.14,1114000,186,True,True
70,2025-03-31,SBI Mutual Fund,12.50,1250000,186,True,True
80,2025-12-31,SBI Mutual Fund,12.50,1250000,186,True,True
81,2025-12-31,ICICI Prudential MF,10.74,1074000,216,True,True

In [76]:
df.drop('num_schemes_anomaly',axis=1,inplace=True)

In [78]:
df.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,aum_lakh_crore_anomaly,aum_crore_anomaly
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,False,False
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,False,False
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,False,False
3,2022-03-31,Nippon India MF,2.70,270000,177,False,False
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,False,False

In [79]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_aum_by_fund_house.csv"),index=False)

In [80]:
df.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,aum_lakh_crore_anomaly,aum_crore_anomaly
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,False,False
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,False,False
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,False,False
3,2022-03-31,Nippon India MF,2.70,270000,177,False,False
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,False,False

In [81]:
df.dtypes

date                      datetime64[ns]
fund_house                        object
aum_lakh_crore                   float64
aum_crore                          int64
num_schemes                        int64
aum_lakh_crore_anomaly              bool
aum_crore_anomaly                   bool
dtype: object

In [85]:
df.describe().iloc[:,1:]

       aum_lakh_crore     aum_crore  num_schemes
count       90.000000  9.000000e+01    90.000000
mean         4.352889  4.352889e+05   152.200000
min          1.050000  1.050000e+05    56.000000
25%          2.525000  2.525000e+05    95.000000
50%          3.450000  3.450000e+05   172.500000
75%          5.675000  5.675000e+05   195.000000
max         12.500000  1.250000e+06   216.000000
std          2.734328  2.734328e+05    52.108832

In [86]:
df  = pd.read_csv(os.path.join(folder,"04_monthly_sip_inflows.csv"))

In [87]:
df.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [88]:
df.dtypes

month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [94]:
df['month']=pd.to_datetime(
    df['month'],
    format='%Y-%m'
)

In [95]:
df.dtypes

month                        datetime64[ns]
sip_inflow_crore                      int64
active_sip_accounts_crore           float64
new_sip_accounts_lakh               float64
sip_aum_lakh_crore                  float64
yoy_growth_pct                      float64
dtype: object

In [96]:
print(len(df))
print(df['yoy_growth_pct'].isnull().sum())

df[['month','yoy_growth_pct']].head(15)

48
12

        month  yoy_growth_pct
0  2022-01-01             NaN
1  2022-02-01             NaN
2  2022-03-01             NaN
3  2022-04-01             NaN
4  2022-05-01             NaN
5  2022-06-01             NaN
6  2022-07-01             NaN
7  2022-08-01             NaN
8  2022-09-01             NaN
9  2022-10-01             NaN
10 2022-11-01             NaN
11 2022-12-01             NaN
12 2023-01-01           20.31
13 2023-02-01           19.66
14 2023-03-01           15.80

In [97]:
# yoy_growth_pct contains 12 missing values corresponding to the first 12 months of data, where year-over-year growth cannot be computed due to the absence of prior-year observations.

In [98]:
df.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01-01,11517,4.91,9.10,4.80,NaN
1,2022-02-01,11438,4.93,8.20,4.85,NaN
2,2022-03-01,12328,5.09,10.50,5.01,NaN
3,2022-04-01,11863,5.48,9.52,5.12,NaN
4,2022-05-01,12286,5.55,8.10,5.15,NaN

In [102]:
cols = df.describe().iloc[:,1:-1].columns

In [103]:
flag_anomaly(cols)

In [104]:
df.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct,sip_inflow_crore_anomaly,active_sip_accounts_crore_anomaly,new_sip_accounts_lakh_anomaly,sip_aum_lakh_crore_anomaly
0,2022-01-01,11517,4.91,9.10,4.80,NaN,False,False,False,False
1,2022-02-01,11438,4.93,8.20,4.85,NaN,False,False,False,False
2,2022-03-01,12328,5.09,10.50,5.01,NaN,False,False,False,False
3,2022-04-01,11863,5.48,9.52,5.12,NaN,False,False,False,False
4,2022-05-01,12286,5.55,8.10,5.15,NaN,False,False,False,False

In [108]:
df['sip_aum_lakh_crore_anomaly']

Empty DataFrame
Columns: [month, sip_inflow_crore, active_sip_accounts_crore, new_sip_accounts_lakh, sip_aum_lakh_crore, yoy_growth_pct, sip_inflow_crore_anomaly, active_sip_accounts_crore_anomaly, new_sip_accounts_lakh_anomaly, sip_aum_lakh_crore_anomaly]
Index: []

In [111]:
df.drop(['sip_inflow_crore_anomaly','active_sip_accounts_crore_anomaly','sip_aum_lakh_crore_anomaly'],axis=1,inplace = True)

In [110]:
df[df['new_sip_accounts_lakh_anomaly']==True]

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct,sip_inflow_crore_anomaly,active_sip_accounts_crore_anomaly,new_sip_accounts_lakh_anomaly,sip_aum_lakh_crore_anomaly
5,2022-06-01,12276,5.60,7.5,5.18,NaN,False,False,True,False
39,2025-04-01,26632,8.38,46.0,13.55,30.73,False,False,True,False

In [112]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_monthly_sip_inflows.csv"),index=False)

In [115]:
df = pd.read_csv(os.path.join(folder,"05_category_inflows.csv"))

In [116]:
df.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [117]:
df.drop_duplicates(inplace=True)

In [118]:
df.dtypes

month                object
category             object
net_inflow_crore    float64
dtype: object

In [119]:
df['month']=pd.to_datetime(
    df['month'],
    format='%Y-%m'
)

In [120]:
df.dtypes

month               datetime64[ns]
category                    object
net_inflow_crore           float64
dtype: object

In [122]:
flag_anomaly(['net_inflow_crore',])

In [124]:
df[df['net_inflow_crore_anomaly']==True]

         month category  net_inflow_crore  net_inflow_crore_anomaly
8   2024-04-01   Liquid           37537.0                      True
20  2024-05-01   Liquid           41872.0                      True
32  2024-06-01   Liquid           40486.0                      True
44  2024-07-01   Liquid           34643.0                      True
56  2024-08-01   Liquid           41952.0                      True
68  2024-09-01   Liquid           35308.0                      True
80  2024-10-01   Liquid           39091.0                      True
92  2024-11-01   Liquid           40506.0                      True
104 2024-12-01   Liquid           34933.0                      True
116 2025-01-01   Liquid           33892.0                      True
128 2025-02-01   Liquid           32374.0                      True
140 2025-03-01   Liquid           38681.0                      True

In [125]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_category_inflows.csv"),index=False)

In [126]:
df = pd.read_csv(os.path.join(folder,"06_industry_folio_count.csv"))

In [127]:
df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [128]:
df.drop_duplicates(inplace=True)

In [129]:
df.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [130]:
df.dtypes

month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [131]:
df['month']=pd.to_datetime(
    df['month'],
    format='%Y-%m'
)

In [135]:
cols = df.describe().columns[1:]

In [136]:
flag_anomaly(cols)

In [138]:
df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore,total_folios_crore_anomaly,equity_folios_crore_anomaly,debt_folios_crore_anomaly,hybrid_folios_crore_anomaly,others_folios_crore_anomaly
0,2022-01-01,13.26,9.28,1.86,0.80,1.33,False,False,False,False,False
1,2022-04-01,13.91,9.74,1.95,0.83,1.39,False,False,False,False,False
2,2022-07-01,13.85,9.69,1.94,0.83,1.38,False,False,False,False,False
3,2022-10-01,14.12,9.88,1.98,0.85,1.41,False,False,False,False,False
4,2023-01-01,14.81,10.37,2.07,0.89,1.48,False,False,False,False,False

In [148]:
df.drop('total_folios_crore_anomaly',axis=1,inplace=True)

In [150]:
df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01-01,13.26,9.28,1.86,0.80,1.33
1,2022-04-01,13.91,9.74,1.95,0.83,1.39
2,2022-07-01,13.85,9.69,1.94,0.83,1.38
3,2022-10-01,14.12,9.88,1.98,0.85,1.41
4,2023-01-01,14.81,10.37,2.07,0.89,1.48

In [151]:
df.describe()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
count,21,21.000000,21.000000,21.000000,21.000000,21.000000
mean,2024-03-31 22:51:25.714285824,19.829524,13.880476,2.776190,1.190000,1.983333
min,2022-01-01 00:00:00,13.260000,9.280000,1.860000,0.800000,1.330000
25%,2023-04-01 00:00:00,15.540000,10.880000,2.180000,0.930000,1.550000
50%,2024-07-01 00:00:00,19.980000,13.990000,2.800000,1.200000,2.000000
75%,2025-04-01 00:00:00,23.890000,16.720000,3.340000,1.430000,2.390000
max,2025-12-01 00:00:00,26.120000,18.280000,3.660000,1.570000,2.610000
std,NaN,4.583376,3.207799,0.640308,0.274864,0.459079

In [152]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_industry_folio_count.csv"),index=False)

In [200]:
df = pd.read_csv(os.path.join(folder,"09_portfolio_holdings.csv"))

In [201]:
df.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [202]:
df.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [203]:
df.dtypes

amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

In [204]:
df['portfolio_date'] = pd.to_datetime(df['portfolio_date'])

In [205]:
df.dtypes

amfi_code                     int64
stock_symbol                 object
stock_name                   object
sector                       object
weight_pct                  float64
market_value_cr             float64
current_price_inr           float64
portfolio_date       datetime64[ns]
dtype: object

In [206]:
df.drop_duplicates(inplace=True)

In [207]:
df.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [208]:
df['stock_symbol'].unique()

array(['POWERGRID', 'HDFCBANK', 'GRASIM', 'DRREDDY', 'ASIANPAINT', 'NTPC',
       'DIVISLAB', 'BHARTIARTL', 'HCLTECH', 'MARUTI', 'INFY', 'ICICIBANK',
       'TATAMOTOR', 'CIPLA', 'BAJFINANCE', 'SUNPHARMA', 'ULTRACEMCO',
       'WIPRO', 'TCS', 'RELIANCE', 'M&M', 'AXISBANK', 'KOTAKBANK',
       'TITAN', 'HINDUNILVR', 'INDUSINDBK', 'NESTLEIND', 'LT', 'SBIN',
       'ADANIPORT'], dtype=object)

In [209]:
df['stock_name'].unique()

array(['Power Grid Corporation', 'HDFC Bank Ltd', 'Grasim Industries Ltd',
       "Dr. Reddy's Laboratories", 'Asian Paints Ltd', 'NTPC Ltd',
       "Divi's Laboratories", 'Bharti Airtel Ltd', 'HCL Technologies Ltd',
       'Maruti Suzuki India Ltd', 'Infosys Ltd', 'ICICI Bank Ltd',
       'Tata Motors Ltd', 'Cipla Ltd', 'Bajaj Finance Ltd',
       'Sun Pharmaceutical Industries', 'UltraTech Cement Ltd',
       'Wipro Ltd', 'Tata Consultancy Services',
       'Reliance Industries Ltd', 'Mahindra & Mahindra Ltd',
       'Axis Bank Ltd', 'Kotak Mahindra Bank', 'Titan Company Ltd',
       'Hindustan Unilever Ltd', 'IndusInd Bank Ltd', 'Nestle India Ltd',
       'Larsen & Toubro Ltd', 'State Bank of India',
       'Adani Ports & SEZ Ltd'], dtype=object)

In [210]:
df['sector'].shape[0]

322

In [211]:
cols = df.describe().columns[1:-1]

In [215]:
# I update flag anomaly here

In [212]:
flag_anomaly(cols)

In [213]:
df.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date,weight_pct_anomaly
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31,False
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31,False
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31,False
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31,False
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31,False

In [214]:
df[df['weight_pct_anomaly']==True]

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date,weight_pct_anomaly
40,119599,GRASIM,Grasim Industries Ltd,Diversified,28.25,1461.32,1872.83,2025-12-31,True
44,100016,WIPRO,Wipro Ltd,IT,25.90,552.43,579.31,2025-12-31,True
64,100033,M&M,Mahindra & Mahindra Ltd,Automobile,26.07,511.03,3852.87,2025-12-31,True
118,118632,BHARTIARTL,Bharti Airtel Ltd,Telecom,30.44,1574.52,6271.17,2025-12-31,True
183,119092,INFY,Infosys Ltd,IT,38.18,1254.80,3939.80,2025-12-31,True
229,101207,SUNPHARMA,Sun Pharmaceutical Industries,Pharma,35.07,285.75,5455.74,2025-12-31,True
245,102885,NTPC,NTPC Ltd,Utilities,28.95,994.90,4140.59,2025-12-31,True
276,148568,SBIN,State Bank of India,Banking,28.61,498.31,2893.58,2025-12-31,True

In [216]:
df.dtypes

amfi_code                      int64
stock_symbol                  object
stock_name                    object
sector                        object
weight_pct                   float64
market_value_cr              float64
current_price_inr            float64
portfolio_date        datetime64[ns]
weight_pct_anomaly              bool
dtype: object

In [217]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_portfolio_holdings.csv"),index=False)

In [218]:
df = pd.read_csv(os.path.join(folder,"10_benchmark_indices.csv"))

In [219]:
df.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [220]:
df.dtypes

date            object
index_name      object
close_value    float64
dtype: object

In [221]:
df.drop_duplicates(inplace=True)

In [222]:
df['index_name'].unique()

array(['NIFTY50', 'NIFTY100', 'NIFTY_MIDCAP150', 'BSE_SMALLCAP',
       'NIFTY500', 'CRISIL_LIQUID', 'CRISIL_GILT'], dtype=object)

In [223]:
df['date'] = pd.to_datetime(df['date'])

In [224]:
df.dtypes

date           datetime64[ns]
index_name             object
close_value           float64
dtype: object

In [228]:
cols = df.describe().columns[1:]

In [229]:
flag_anomaly(cols)

In [230]:
df.head()

        date index_name  close_value  close_value_anomaly
0 2022-01-03    NIFTY50     17492.79                False
1 2022-01-04    NIFTY50     17689.64                False
2 2022-01-05    NIFTY50     17835.05                False
3 2022-01-06    NIFTY50     17878.51                False
4 2022-01-07    NIFTY50     17759.15                False

In [235]:
df.shape

(8050, 4)

In [236]:
fol = os.path.dirname(folder)
savePath = os.path.join(fol,"processed")
df.to_csv(os.path.join(savePath,"c_benchmark_indices.csv"),index=False)